about/urls.py
from django.urls import path
from . import views

app_name = "about"

urlpatterns = [
    path('', views.about_view, name="about")
]

accounts/urls.py
from django.urls  import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name="login"),
    path('password_reset/', views.CustomPasswordResetFormView.as_view(), name="password_reset"),
    path('reset/<uidb64>/<token>/', views.CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path('password_change/', views.CustomPasswordChangeView.as_view(), name="password_change"),
    path('', include('django.contrib.auth.urls')),
    path('', views.home, name="home"),
    path('message', views.message, name="message"),
    path('create_account/', views.user_registration, name="user_registration"),
    path('edit_profile', views.profile, name="profile")
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

blogs/urls.py
from django.urls import path
from .import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blogs'
urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('projects/', include('projects.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('about/', include('about.urls', namespace='about'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

accounts/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    message=models.TextField()
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.name} has written a message"
    
    class Meta:
        ordering = ['-published']
        indexes = [
            models.Index(fields=['-published'])
            ]

class Profile(models.Model):
    user = models.OneToOneField(
        get_user_model(),
        related_name='profile',
        on_delete=models.CASCADE
    )
    photo = models.ImageField(upload_to='profiles/%Y/%m/%d/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.user} profile has been created"
    
    class Meta:
        ordering = ['user']
        indexes = [
            models.Index(fields=['user'])
            ]

accounts/forms.py
from django import forms
from .models import Contact, Profile
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm

class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Old password','class':'form-control rounded-0'}), label="Old password")
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'New Password','class':'form-control rounded-0'}), label="New password")
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Repeat New Password','class':'form-control rounded-0'}), label="New password confirmation")

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder':'example@gmail.com','class':'form-control rounded-0'}))
    
class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password','class':'form-control'}), label="New password")
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Repeat Password','class':'form-control'}), label="New password confirmation")

class CustomLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder':'Username or Email','class':'form-control rounded-0'}), label="Username or Email")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder':'Password', 'class':'form-control rounded-0'}))

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control rounded-0', 'placeholder':'Enter Name'}),
            'email': forms.EmailInput(attrs={'class':'form-control rounded-0', 'placeholder': 'example@gmail.com'}),
            'message': forms.Textarea(attrs={'class': 'form-control rounded-0', 'placeholder':'Enter Message', 'name':'message'})
        }
 
User = get_user_model()       
class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder":"Password","class":"form-control rounded-0"}))
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput(attrs={"placeholder":"Repeat Password","class":"form-control rounded-0"}))
    
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'username', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control rounded-0', 'placeholder': 'First Name', }),
            'last_name': forms.TextInput(attrs={'class':'form-control rounded-0', 'placeholder':'Last Name'}),
            'username': forms.TextInput(attrs={'class':"form-control rounded-0", 'placeholder':'username'}),
            'email': forms.EmailInput(attrs={"class":'form-control rounded-0', 'placeholder': 'Email'})
        }
        
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError("Passwords do not match")
        return cd['password2']
    
    def clean_email(self):
        cd = self.cleaned_data
        email = User.objects.filter(email=cd['email']).exists()
        if email:
            raise forms.ValidationError("Email already exists.")
        return cd['email']
    
class EditProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']
        widgets = {
            'photo': forms.FileInput(attrs={'class':'form-control rounded-0'})
        }
        
class EditUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={'class':'form-control rounded-0'}),
            'last_name': forms.TextInput(attrs={'class':'form-control rounded-0'}),
            'email': forms.EmailInput(attrs={'class':'form-control rounded-0'})
        }
        

accounts/views.py
from django.shortcuts import render
from .forms import ContactForm, UserRegistrationForm, EditProfileForm, EditUserForm, CustomLoginForm, CustomPasswordResetForm, CustomSetPasswordForm, CustomPasswordChangeForm
from django.core.mail import send_mail
from django.views.decorators.http import require_POST
from .models import Profile
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView,PasswordResetView, PasswordResetConfirmView, PasswordChangeView

class CustomLoginView(LoginView):
    template_name = 'registration/login.html'
    authentication_form = CustomLoginForm
    
class CustomPasswordResetFormView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    form_class = CustomPasswordResetForm
    
class CustomPasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_confirm.html'
    form_class = CustomSetPasswordForm
    
class CustomPasswordChangeView(PasswordChangeView):
    template_name='registration/password_change_form.html'
    form_class = CustomPasswordChangeForm
    
def home(request):
    return render(
        request,
        "account/home.html",
        { 'section':'dashboard'}
    )
    
def message(request):
    message = None
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            message = form.save(commit=False)
            message.body = cd['message']
            message.save()
            messages.success(request, "Your message has been sent successfully")
            send_mail(
                f"Contact from {cd['name']}",
                f"{cd['message']} by {cd['email']}",
                cd['email'],
                ['osorabrian@gmail.com']
            )
        else:
            messages.error(request, "Sorry! There was an error sending your message.")
    else:
        form = ContactForm()
    
    return render(
        request,
        'account/contact.html',
        {'form':form, 'message':message}
    )
 
def user_registration(request):
    if request.method == "POST":
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = form.save(commit=False)
            user.set_password(cd['password'])
            user.save()
            Profile.objects.create(user = user)
            messages.success(request, "Account created successfully.")
            return render(
                request,
                'account/user_registration_done.html',
                {'user': user}
            )
        else:
            messages.error(request, "Sorry! There is an error creating an account.")
    else:
        form = UserRegistrationForm()
            
    return render(
        request,
        'account/user_registration.html',
        {'form':form}
    )
  
@login_required  
def profile(request):
    if request.method == "POST":
        user_form = EditUserForm(instance = request.user, data = request.POST)
        profile_form = EditProfileForm(instance = request.user.profile ,data = request.POST, files=request.FILES)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Profile has been updated successfully.")
            return render(
                request,
                'account/profile_edited.html'
            )
        else:
            messages.error(request, "Error in updating your profile.")
    else:
        user_form = EditUserForm(instance = request.user)
        profile_form = EditProfileForm(instance = request.user.profile)
        
    return render(
        request,
        'account/edit_profile.html',
        {'user_form': user_form, 'profile_form': profile_form}
    )

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en-us">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Brian Osora Isaboke Portfolio">
    <meta name="keywords" content="Brian, Osora, Isaboke">
    <meta name="author" content="Brian Osora Isaboke">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/index.css' %}" rel="stylesheet" type="text/css" />
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/3b3d0030d7.js" crossorigin="anonymous"></script>
</head>

<body class="bg-black text-white">

    <nav class="navbar navbar-expand-lg">
      <div class="container-fluid">

      <h1><a href="{% url "home" %}" id="my-name" class="navbar-brand">Brian Osora</a></h1>
      <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          {% comment %} {% if request.user.is_authenticated %} {% endcomment %}
            <ul class="navbar-nav mx-auto">
              <li class="nav-item"><a href="{% url "about:about" %}" class="nav-link text-white fs-5 {% if request.resolver_match.url_name == 'about' %}active{% endif %}">About</a></li>
              <li class="nav-item"><a href="{% url "projects" %}" class="nav-link text-white fs-5 {% if request.resolver_match.url_name == 'projects' %}active{% endif %}">Projects</a></li>
              <li class="nav-item"><a href="{% url "blogs:post_list" %}" class="nav-link text-white fs-5 {% if request.resolver_match.namespace == 'blogs' %}active{% endif %}">Blogs</a></li>
            </ul>
{% comment %} 
              <ul class="navbar-nav">
                <li class="nav-item dropdown mt-2">

                  <button class="dropdown text-white d-flex text-decoration-none bg-transparent border-0" data-bs-toggle="dropdown" aria-expanded="false">
                    {% if request.user.profile.photo %}
                      <img src={{request.user.profile.photo.url}} alt="{{request.user.profile.user}}" height="40" width="40" style="border-radius:50%; object-fit: contain"/>
                    {% else %}
                      <img src="{% static "images/avatar.png"%}" alt="avatar" height="40" width="40" style="border-radius:50%"/>
                    {% endif %}
                    <p class="ms-2 fs-5">{{request.user.username}}</p>
                    <i class="fa-solid fa-chevron-down mt-2" style="color: #ffffff;font-size:15px;margin-left:8px;margin-right:10px"></i>
                  </button>

                  <ul class="dropdown-menu" id="dropdown-menu">
                    <li><a href="{% url "profile" %}" class="dropdown-item text-white bg-transparent nav-link">Edit Profile</a></li>
                    <hr>
                    <li><a href="{% url "password_change"%}" class="dropdown-item text-white bg-transparent nav-link">Change Password</a></li>
                    <hr>
                    <li>
                      <form method="post" action={% url "logout" %}>
                        <input type="submit" name="logout" id="logout" value="Log Out" class="dropdown-item text-white bg-transparent"/>
                        {% csrf_token %}
                      </form>
                    </li>
                  </ul>
                  
                </li>
              </ul>
            {% else %}
              <ul class="navbar-nav ms-auto">
                <a href="{% url "login" %}" class="auth-nav nav-link text-white mt-2 nav-text {% if request.resolver_match.url_name == 'login' %}active{% endif %}">Log In</a>
                <a href="{% url "user_registration" %}" class="auth-nav nav-link text-white mt-2 {% if request.resolver_match.url_name == 'user_registration' %}active{% endif %}">Sign Up</a>
              </ul>
          {% endif %} {% endcomment %}
      </div>
      </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
          <div style="text-align: center" class="mb-4 mt-4">
            <ul>
              <l1 id="message">{{message}}</li>
            </ul>
        </div>
        {% endfor %}
    {% endif %}
    
    {% block content %}
    {% endblock %}
    
    <footer>
      <div id="socials">
        <a class="icon-white" href="https://github.com/Osorabrian" title="Github">        
          <img src="https://cdn.jsdelivr.net/npm/feather-icons@4.29.1/dist/icons/github.svg" alt="GitHub Icon" width="24" height="24" />
        </a>
        <a class="icon-white" href="https://x.com/BryanOsora" title="X">
          <img src="https://cdn.jsdelivr.net/npm/feather-icons@4.29.1/dist/icons/twitter.svg" alt="X (Twitter) Icon" width="24" height="24" />
        </a>
        <a class="icon-white" href="mailto:osorabrian@gmail.com" title="Email">
          <img src="https://cdn.jsdelivr.net/npm/feather-icons@4.29.1/dist/icons/mail.svg" alt="Mail Icon" width="24" height="24" />
        </a>
        <a class="icon-white" href="tel:+6692356809" title="Phone">
          <img src="https://cdn.jsdelivr.net/npm/feather-icons@4.29.1/dist/icons/phone.svg" alt="Phone Icon" width="24" height="24" />
        </a>
      </div>
    </footer>  
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>

</html>